## SITE VARIABLES ##
title: The Baltimore Transgender Alliance
author: Evan Lori Mahone
email: evan@bmoretransalliance.com
description: The Baltimore Transgender Alliance's Home Page on the Web

company: The Baltimore Transgender Alliance
summary: 'We work to uplift the voices of transgender and gender non-conforming people in Baltimore City and continually center our communityâ€™s needs in broader political conversations.'
copyright_year: 2017
address:
 - '2530 North Charles Street'
 - '3rd Floor - Room 1'
 - 'Baltimore, MD 21218'

donate_link: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=PA6KVG928CME2
cloud_name: bmoretransalliance


## CONFIGUTATION STUFF ##
sass:
  style: expanded
  sass_dir: _sass

tag_page_layout: tag-page
tag_page_dir: tag

include:
 - _pages

exclude:
 - vendor

# Explicitly turn off the old code
paginate: nil
paginate_path: nil

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
   before: 2
   after: 2

fetch_resources_data: true

collections:
  people:
   output: true
   permalink: /:collection/:slug
  orgs:
   output: true
   permalink: /:collection/{slug}
  projects:
   name: Example
   email: example@example.com
